//
//  Categorie.swift
//
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct RoomCall: JSONCompatible {
    var catImage: String
    var titleCat: String
    var detailCat: String


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        catImage = json["catImage"] as? String ?? ""
        titleCat = json["titleCat"] as? String ?? ""
        detailCat = json["detailCat"] as? String ?? ""
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(catImage: String, titleCat: String, detailCat: String) {
        self.catImage = catImage
        self.titleCat = titleCat
        self.detailCat = detailCat
    }



    func jsonDictionary(useOriginalJsonKey: Bool) -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["catImage"] = catImage
        dict["titleCat"] = titleCat
        dict["detailCat"] = detailCat
        return dict
    }



}



