//
//  Song.swift
//
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct RoomChat: JSONCompatible {
    var roomImage: String
    var roomDetail: String
    var roomTitle: String


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        roomImage = json["roomImage"] as? String ?? ""
        roomDetail = json["roomDetail"] as? String ?? ""
        roomTitle = json["roomTitle"] as? String ?? ""
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(roomImage: String, roomDetail: String, roomTitle: String) {
        self.roomImage = roomImage
        self.roomDetail = roomDetail
        self.roomTitle = roomTitle
    }



    func jsonDictionary(useOriginalJsonKey: Bool) -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["roomImage"] = roomImage
        dict["roomDetail"] = roomDetail
        dict["roomTitle"] = roomTitle
        return dict
    }



}



